on:
    pull_request:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    optimize_ci:
        runs-on: ubuntu-latest
        outputs:
            skip: ${{ steps.check_skip.outputs.skip }}
        steps:
            - name: Optimize CI
              id: check_skip
              uses: withgraphite/graphite-ci-action@main
              with:
                  graphite_token: ${{ secrets.GRAPHITE_OPTIMISE_CI_SECRET }}

    ci:
        needs: optimize_ci
        if: needs.optimize_ci.outputs.skip == 'false'

        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
            - run: echo "Hello World"
